#!/bin/bash

set -e;

gcloud services enable bigquery.googleapis.com;
gcloud services enable dataflow.googleapis.com;
gcloud services enable compute.googleapis.com;
gcloud services enable pubsub.googleapis.com;
gcloud services enable storage.googleapis.com;